/**
 * Release manifest — generated by scripts/build-manifest.py during CI.
 * Lists every file in the release with sizes so the cache layer knows
 * what to download and can report progress accurately.
 */
export interface Manifest {
  readonly files: ReadonlyArray<ManifestFile>;
  readonly totalSize: number;
}

export interface ManifestFile {
  /** Relative path within the release archive (e.g. "bin/rustc.wasm"). */
  readonly path: string;
  /** File size in bytes. */
  readonly size: number;
}

/**
 * Fetch and parse the manifest for a given release version.
 *
 * The manifest is uploaded as a separate asset alongside rustc-wasm.tar.gz
 * in each GitHub Release. The URL pattern is:
 *   ${releaseUrl}/manifest.json
 *
 * @param releaseUrl — the base URL for the release assets
 *   (e.g. "https://github.com/Mearman/wasm-rustc/releases/download/rustc-wasm-abc123")
 */
export async function fetchManifest(releaseUrl: string): Promise<Manifest> {
  const url = `${releaseUrl}/manifest.json`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch manifest from ${url}: ${response.status} ${response.statusText}`,
    );
  }
  const data: unknown = await response.json();
  return validateManifest(data);
}

function validateManifest(data: unknown): Manifest {
  if (typeof data !== "object" || data === null) {
    throw new Error("Manifest must be an object");
  }
  if (!("files" in data) || !Array.isArray(data.files)) {
    throw new Error("Manifest must have a 'files' array");
  }
  if (!("totalSize" in data) || typeof data.totalSize !== "number") {
    throw new Error("Manifest must have a 'totalSize' number");
  }
  const files = data.files.map((f: unknown) => {
    if (typeof f !== "object" || f === null) {
      throw new Error("Each manifest file entry must be an object");
    }
    if (!("path" in f) || typeof f.path !== "string") {
      throw new Error("Each manifest file entry must have a 'path' string");
    }
    if (!("size" in f) || typeof f.size !== "number") {
      throw new Error("Each manifest file entry must have a 'size' number");
    }
    return { path: f.path, size: f.size };
  });
  return { files, totalSize: data.totalSize };
}
